### PR TITLE
Save Tracker Hits

### PR DESCRIPTION
**Pull request by vvolkl**

### CODE REVIEW

**Comment by clementhelsens** [comment]
Hi Valentin, have you been able to test the size increase with high energetic events?

**Comment by vvolkl** [comment]
Hi, no, but I'll do it right away if you point me to a suitable gen sample!

**Comment by clementhelsens** [comment]
Sure, 
can you can run
python send.py --physics --process top --pt 1000 -n 1 -N 1 --lsf
with and w/o the tracker hits?

**Comment by vvolkl** [comment]
It seems that the two produced events look very differently (cpu usage, etc.) regardless of the tracker hits

The files I get are
```
-rw-r--r--. 1 vavolkl def-cg 1.4M Feb  8 17:15 output_lsf_vavolkl_201802081606578858.root # without tracker
-rw-r--r--. 1 vavolkl def-cg 6.8K Feb  8 19:45 output_lsf_vavolkl_201802081733164268.root # with tracker
```

which doesn't make much sense to me. I'll try to increase the number of events

**Comment by clementhelsens** [comment]
Hi Valentin, 

it does not make sense indeed, but I expect that the second file is corrupted, ie the job crashed. This is what I mentioned during one of the last FCCSW meeting that I observe such behaviour sometime, and I don't know how to reproduce the problem to debug it. You could first have a look at the log files from LSF? they are written in the directory where you sent the jobs (LSF_<JOBID>/STDOUT)
Can you also try to run both jobs locally? For that you just need to execute the scripts that have been written in BatchOutputs I guess (unless you used an other --log dir)
Maybe remove the part in those scripts that copy the output and rm the job, so that you keep the local file.

**Comment by vvolkl** [comment]
Hi Clement,

thanks for the suggestions! I finally managed to run the job locally with identical seed. The files I get are 

```
rw-r--r--. 1 vavolkl def-cg 3.2M 14. Feb 23:27 output_lsf_vavolkl_201802081606578858.root
-rw-r--r--. 1 vavolkl def-cg 2.8M 14. Feb 23:28 output_lsf_vavolkl_201802081606578858_without_trackhits.root
```

a 0.4 Megabyte increase due to the 3x10^4 trackhits saved in addition. It doesn't seem to be completely unrealistic to start saving the trackhits, but as discussed I would suggest to also save the entry- and exit points of the track in the sensitive material, to be able to support more complex digitization studies. This means saving an additional 6 doubles, wich would probably increase the additional data volume by a factor of 3. I'll see that I quickly implement the savetool, and check!

**Comment by clementhelsens** [comment]
Hi Valentin, 

I think it is reasonable. for the time being I'll merge your request, waiting for the development you mention.

**Pull request merged**
